# Homework 1
## Recognising Digits

In [1]:
import numpy as np

class Hopfield():
    """
    Creates a Hopfield Network.
    """
    def __init__(self):
        self.weights = None

    def hebbs_rule(self, stored_patterns, diagonal_set_to_zero=True):
        """
        Generates the weight matrix for the stored patterns.
        """
            
        num_bits = len(stored_patterns[0]) 
        self.weights = (1/num_bits)* np.dot(stored_patterns.T,
                                            stored_patterns) 
        if diagonal_set_to_zero == True:
            for k in range(len(stored_patterns[0])):
                self.weights[k][k] = 0
            
        return self.weights
    
    def deterministic_asynchronous(self, index_neuron, feed_pattern): 
        """
        Makes one asynchronous update to a choosen neuron in one fed pattern.
        """
        
        original_neuron = feed_pattern[index_neuron]
        updated_neuron = int(np.sign(np.dot(self.weights[index_neuron].T,
                                            feed_pattern.T)))

        feed_pattern[index_neuron] = updated_neuron
        
        return original_neuron, updated_neuron, feed_pattern


In [2]:
   def recognise_pattern(stored_patterns, feed_pattern):
        """
        This function creates a Hopfield Network that stores the patterns: 
        stored_patterns. The function feeds the pattern: 
        feed_pattern and check if it converges to any of the stored patterns. 
        The function returns the index for the pattern to witch the network 
        converges and also the actuall pattern that the network converges to.
        """
        # Creates the Hopfield Network and weight matrix
        digits = Hopfield()
        print(digits.hebbs_rule(stored_patterns))


        # Creates an empty matrix.
        state = [[] for i in range(len(feed_pattern[0]))]

        # Repeates the update 100 times, by now steady-state should be reached
        for trial in range(100):
        # Fills the empty matrix with the states after each deterministic update.
            for i in range(len(feed_pattern[0])):
                state[i] = digits.deterministic_asynchronous(i, 
                                                        feed_pattern[0])[2]

        # The last state is the state to witch the network has converged to.
        pattern_converge = state[len(feed_pattern[0])-1]

        for i in range(len(original_patterns)):
            if np.all(pattern_converge == stored_patterns[i]):
                return i, pattern_converge.reshape(16,10)


In [3]:
#Patterns that should be fed to the network.
x1=[[ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
    [ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
    [ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
    [ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
    [ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
    [ -1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, -1, -1, -1, -1, -1, -1, -1] ];

x2=[[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],
    [ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[ -1, -1, -1, 1, 1, 1, 1, -1, -1, -1] ];

x3=[[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],
    [ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],
    [ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],
    [ -1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],
    [ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
    [ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
    [ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[ 1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
    [ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[ 1, 1, 1, 1, 1, 1, 1, 1, -1, -1] ];

x4=[[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],
    [ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, 1, 1, 1, -1],
    [ -1, -1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, 1, 1, 1, 1, 1, 1, -1, -1] ];

x5=[[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],
    [ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],
    [ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],
    [ -1, 1, 1, -1, -1, -1, -1, 1, 1, -1],[ -1, 1, 1, 1, 1, 1, 1, 1, 1, -1],
    [ -1, 1, 1, 1, 1, 1, 1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],
    [ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1],[ -1, -1, -1, -1, -1, -1, -1, 1, 1, -1] ];

original_patterns = [x1, x2, x3, x4, x5]
#reshapes the patterns to a 1x160 matrix
reshaped_patterns = np.array([np.array(i).reshape(-1,) 
                              for i in original_patterns])

In [6]:
# The given patterns that should be feed one at a time to the network.
feed1=[[-1, -1, -1, -1, -1, -1, -1, -1, 1, 1],[1, 1, 1, 1, 1, 1, 1, 1, -1, -1],
       [-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[-1, -1, -1, -1, -1, 1, 1, 1, -1, -1], 
       [-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[-1, -1, -1, -1, -1, 1, 1, 1, -1, -1], 
       [-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[1, 1, 1, 1, 1, 1, 1, 1, -1, -1], 
       [1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[1, 1, 1, -1, -1, -1, -1, -1, -1, -1], 
       [1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[1, 1, 1, -1, -1, -1, -1, -1, -1, -1], 
       [1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[1, 1, 1, -1, -1, -1, -1, -1, -1, -1], 
       [1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[1, 1, 1, 1, 1, 1, 1, 1, -1, -1]]

feed2=[[1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[1, 1, 1, 1, 1, 1, 1, 1, -1, -1], 
       [-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],
       [-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],
       [-1, -1, -1, -1, -1, 1, 1, 1, -1, -1],[1, 1, 1, 1, 1, 1, 1, 1, -1, -1],
       [1, 1, 1, 1, 1, 1, 1, 1, -1, -1],[1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
       [1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
       [1, 1, 1, -1, -1, -1, -1, -1, -1, -1],[1, 1, 1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, 1, 1],[-1, -1, -1, -1, -1, -1, -1, -1, 1, 1]]

feed3=[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],[1, 1, 1, -1, -1, -1, -1, 1, 1, 1],
       [-1, -1, 1, 1, 1, 1, 1, 1, -1, -1],[-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
       [-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
       [-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
       [-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
       [-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],
       [-1, 1, 1, 1, -1, -1, 1, 1, 1, -1],[-1, -1, 1, 1, 1, 1, 1, 1, -1, -1],
       [-1, -1, -1, 1, 1, 1, 1, -1, -1, -1],[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]]

# Reshapes the pattern that should be fed to the network
feed1= np.array(feed1).reshape(1,-1)
feed2= np.array(feed2).reshape(1,-1)
feed3= np.array(feed3).reshape(1,-1)

In [7]:
# First output is the index of the pattern that the network converges to. 
# Second output is the steady pattern that the network reaches based on the fed pattern
recognise_pattern(reshaped_patterns,feed1) 

[[ 0.       0.01875  0.00625 ...  0.00625  0.00625  0.01875]
 [ 0.01875  0.       0.01875 ...  0.01875  0.01875  0.00625]
 [ 0.00625  0.01875  0.      ...  0.03125  0.00625 -0.00625]
 ...
 [ 0.00625  0.01875  0.03125 ...  0.       0.00625 -0.00625]
 [ 0.00625  0.01875  0.00625 ...  0.00625  0.       0.01875]
 [ 0.01875  0.00625 -0.00625 ... -0.00625  0.01875  0.     ]]


(2, array([[ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
        [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
        [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
        [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
        [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
        [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
        [-1, -1, -1, -1, -1,  1,  1,  1, -1, -1],
        [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
        [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
        [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
        [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
        [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
        [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
        [ 1,  1,  1, -1, -1, -1, -1, -1, -1, -1],
        [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1],
        [ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1]]))